### ISSUE TITLE
Information about the different images

### ISSUE THREAD

**Issue by elpiel** [ArduPilot/ardupilot_dev_docker#1]
It would be great to have additional information on what the images contain and how they can be used. Are they supposed to be used for development of ardupilot only?

I am looking for a way to have a docker-compose setup running ardupilot & simulation, instead of installing all the software on my laptop and potentially running simulations on CI.
However I am not really sure which image to use and how, so this would be great info for me and probably others.

**Comment by khancyr** [comment]
Hello,

Those are mostly intend to run on our CI system. I will put more comments to details each image.
The most conveniant way to use SITL in docker would be to use the docker image into the ardupilot directy, build SITL and use a multi stage build to get only what you need from the main directory : SITL dependency is just libc ! (you need python if you want sim_vehicle.py)

**Comment by khancyr** [comment]
it should be better now ! Closing

**Comment by elpiel** [comment]
Thank you!
